services:
  proxy:
    image: nginx:alpine
    container_name: art_nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/ssl:ro
    depends_on:
      - backend
      - admin
    restart: unless-stopped
    networks:
      - artnepalaya-net

  backend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: art_backend
    env_file:
      - .env.production
    expose:
      - "8080"
    depends_on:
      mongodb:
        condition: service_started
      redis:
        condition: service_started
      postgresql:
        condition: service_started
    restart: unless-stopped
    networks:
      - artnepalaya-net
    deploy:
      resources:
        limits:
          memory: 1G

  admin:
    build:
      context: ../admin
      dockerfile: Dockerfile
    container_name: art_admin
    restart: unless-stopped
    networks:
      - artnepalaya-net

  mongodb:
    image: mongo:7.0
    container_name: art_mongodb
    env_file:
      - .env.production
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    networks:
      - artnepalaya-net

  postgresql:
    image: postgres:16-alpine
    container_name: art_postgresql
    env_file:
      - .env.production
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - artnepalaya-net

  redis:
    image: redis:7.2-alpine
    container_name: art_redis
    env_file:
      - .env.production
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - artnepalaya-net

networks:
  artnepalaya-net:
    driver: bridge

volumes:
  mongodb_data:
  postgresql_data:
  redis_data: